class_name Game
extends Node2D
## Root of the game. Starting point generated by tools/new_game.py; replace freely, but keep
## the testing contract below, which the harness and tests/e2e rely on:
##   - start_match(seed): restart from scratch, deterministically (clears %Entities, resets
##     every autoload that holds match state).
##   - state_name(): a readable state for wait_until(...) in tests; signals (match_started,
##     state_changed) for g.watch(...).
##   - Randomness only through _rng (seeded); animations driven by accumulated delta, never by
##     the system clock (otherwise screenshots differ between runs). `gdh lint` checks both.
##   - Everything spawned during a match goes under %Entities, never into the root.
##   - debug_* methods: test-only shortcuts (set up a situation in one call).
## Architecture rules (call down / signal up, data in Resources, no state in autoloads):
## .claude/skills/godot-agent-dev/references/architecture.md

signal match_started(seed_value: int)
signal state_changed(from: String, to: String)

enum State { PLAYING, WON }

const SPEED := 220.0

## Fixed seed; -1 picks one at random. Also settable with `godot ... -- --seed=N`.
@export var match_seed := -1

var state := State.PLAYING
var current_seed := 0
var player_position := Vector2.ZERO

var _rng := RandomNumberGenerator.new()
var _time := 0.0

@onready var _entities: Node2D = %Entities


func _ready() -> void:
	var seed_value := match_seed
	for arg in OS.get_cmdline_user_args():
		if arg.begins_with("--seed="):
			seed_value = int(arg.trim_prefix("--seed="))
	start_match(seed_value)


func start_match(seed_value: int = -1) -> void:
	if seed_value < 0:
		seed_value = randi() % 1000000  # gdh: allow(global-rng) choosing the seed itself
	current_seed = seed_value
	_rng.seed = seed_value
	for child in _entities.get_children():
		_entities.remove_child(child)
		child.queue_free()
	_set_state(State.PLAYING)
	_time = 0.0
	player_position = Vector2(_rng.randf_range(200, 1080), 360)
	queue_redraw()
	match_started.emit(seed_value)


func state_name() -> String:
	return State.keys()[state]


func _set_state(new_state: State) -> void:
	if new_state == state:
		return
	var old := state_name()
	state = new_state
	state_changed.emit(old, state_name())


func _physics_process(delta: float) -> void:
	_time += delta
	var input := Input.get_vector("move_left", "move_right", "move_up", "move_down")
	player_position += input * SPEED * delta
	queue_redraw()


func _draw() -> void:
	draw_rect(Rect2(Vector2.ZERO, get_viewport_rect().size), Color(0.12, 0.14, 0.2))
	var pulse := 1.0 + sin(_time * 4.0) * 0.08
	draw_circle(player_position, 20.0 * pulse, Color(1.0, 0.75, 0.3))
	draw_string(ThemeDB.fallback_font, Vector2(20, 40), "Nuevo Juego  ·  WASD / flechas", HORIZONTAL_ALIGNMENT_LEFT, -1, 20)


# --- Test/debug helpers -------------------------------------------------------------------

## Test helper: puts the player somewhere specific.
func debug_place_player(x: float, y: float) -> void:
	player_position = Vector2(x, y)


## Test helper: ends the match as won.
func debug_win() -> void:
	_set_state(State.WON)
